name: CI
on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1

        - name: instalando as dependências
          run: npm install

        - name: executando o lint para verificar se a erros
          run: npx eslint .

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: jest
        uses: stefanoeb/jest-action@1.0.4
        run: npm run test

