name: workflow

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  # tests-integration:
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v2.2.0
  #       with:
  #         node-version: ${{ matriz.node-version }}

  #     - name: Install dependencies
  #       run: npm install
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14


        - name: instalando as dependências
          run: npm install

        - name: executando o lint para verificar se a erros
          run: npx eslint .
